add customized feature
SIXIN-LI/MovieClub pull request #14
Opened 2023-03-15 23:46 UTC by xiaoxiaoliu2022

add advances feature customize search

2023-03-16 21:14 UTC, SIXIN-LI requested changes
如果觉得太多完不成的话，只实现views delete的话，也得先写好get哦。
如果是能写完的话，那还是把dao都修改好了，再一次merge吧

2023-03-16 21:14 UTC, SIXIN-LI commented on src/main/java/movie/dao/MovieViewsDao.java
> +		List<MovieViews> movieViews = new ArrayList<MovieViews>();
personal view history 需要 by userId

2023-03-16 21:14 UTC, SIXIN-LI commented on src/main/java/movie/dao/MovieViewsDao.java
> +		Connection connection = null;
如果有view ID（唯一），就不用user id了吧。

2023-03-16 21:14 UTC, SIXIN-LI commented on src/main/java/movie/dao/CustomizedSearchDao.java
> +		List<Movies> ratingAndGenreMovies = new ArrayList<Movies>();
还需要 by genre 和by rating 的get

2023-03-16 23:20 UTC, xiaoxiaoliu2022 commented
更新了， 你们再看看可不可以

2023-03-17 04:05 UTC, zhangsisi0717 approved these changes

2023-03-17 18:53 UTC, SIXIN-LI commented on src/main/java/movie/dao/CustomizedSearchDao.java
> +
这个评分是不是应该是大于呀。我记得那天说的是，大于这个评分的电影。

2023-03-17 18:54 UTC, SIXIN-LI approved these changes

2023-03-22 04:25 UTC, zhangsisi0717 approved these changes

2023-03-22 04:28 UTC, merged